INFO - main:111 - ['sub-00004', 'sub-00005', 'sub-00006', 'sub-00007']
INFO - main:134 - __________________sub-00004 ses-02 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [1483874, 1498314, 1531805, 1546245, 1767384, 3147349, 4544803, 5980757, 7725142]
INFO - main:184 - * stop_df: [1485873, 1500313, 1533803, 1548243, 2835658, 4215623, 5613077, 7049030, 8370217]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [1768304, 3148269, 4545723, 5981677, 7726062]
INFO - main:201 - * adjusted stop_df: [2835659, 4215624, 5613078, 7049032, 8370218]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00004 ses-03 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 10540
INFO - main:183 - * start_df: [2079171, 2093611, 2127426, 2141866, 2398254, 3765051, 5308766, 6807280, 8565572, 12424473, 13352779]
INFO - main:184 - * stop_df: [2081170, 2095610, 2129425, 2143865, 3466527, 4833324, 6377039, 7875553, 12334950, 13253547, 14181853]
INFO - main:185 - * total of 11 runs
INFO - main:200 - * adjusted start_df: [2399174, 3765971, 5309686, 6808200, 8566492, 12425393, 13353699]
INFO - main:201 - * adjusted stop_df: [3466528, 4833325, 6377041, 7875554, 12334952, 13253548, 14181855]
INFO - main:202 - * total of 7 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00004 ses-04 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 3821
INFO - main:183 - * start_df: [2089802, 2104242, 2138134, 2152574, 2412300, 3860986, 5432713, 6799779]
INFO - main:184 - * stop_df: [2091801, 2106241, 2140133, 2154573, 3480574, 4929260, 6500986, 7110896]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [2413220, 3861906, 5433633, 6800699]
INFO - main:201 - * adjusted stop_df: [3480575, 4929261, 6500988, 7110897]
INFO - main:202 - * total of 4 runs
INFO - main:217 - runs shorter than 300 sec: sub-00004 ses-04 [3] - run number in python order
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00004 ses-05 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [4664179, 4678618, 4712456, 4726896, 5002068, 6732716, 8363668, 9821219]
INFO - main:184 - * stop_df: [4666177, 4680617, 4714455, 4728895, 6070342, 7800989, 9431941, 10889492]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [5002988, 6733636, 8364588, 9822139]
INFO - main:201 - * adjusted stop_df: [6070343, 7800990, 9431942, 10889493]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00004 ses-06 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [1491521, 1505961, 1540185, 1554625, 1796603, 3233541, 4597066, 5994266, 7584365]
INFO - main:184 - * stop_df: [1493520, 1507960, 1542183, 1556623, 2864877, 4301814, 5665339, 7062539, 8229440]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [1797523, 3234461, 4597986, 5995186, 7585285]
INFO - main:201 - * adjusted stop_df: [2864878, 4301816, 5665341, 7062540, 8229442]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00004 ses-07 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [2652105, 2666545, 2700110, 2714550, 2966342, 4392667, 5785937, 7175227]
INFO - main:184 - * stop_df: [2654104, 2668544, 2702108, 2716548, 4034615, 5460940, 6854209, 8243500]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [2967262, 4393587, 5786857, 7176147]
INFO - main:201 - * adjusted stop_df: [4034616, 5460941, 6854211, 8243501]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00004 ses-08 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [2543337, 2557777, 2591429, 2605869, 2891101, 4293333, 5992643, 7353896, 8893015]
INFO - main:184 - * stop_df: [2545336, 2559776, 2593428, 2607867, 3959375, 5361606, 7060916, 8422169, 9538090]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [2892021, 4294253, 5993563, 7354816, 8893935]
INFO - main:201 - * adjusted stop_df: [3959376, 5361607, 7060917, 8422170, 9538092]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00004 ses-09 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [1468165, 1482605, 1516188, 1530628, 1726937, 3150169, 4677605, 6029791]
INFO - main:184 - * stop_df: [1470164, 1484604, 1518187, 1532627, 2795210, 4218442, 5745878, 7098064]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [1727857, 3151089, 4678525, 6030711]
INFO - main:201 - * adjusted stop_df: [2795212, 4218444, 5745880, 7098066]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00004 ses-10 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [2225390, 2239830, 2273484, 2287923, 2515812, 3986006, 5432908, 7009234, 8502443]
INFO - main:184 - * stop_df: [2227388, 2241828, 2275482, 2289922, 3584085, 5054279, 6501181, 8077507, 9147518]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [2516732, 3986926, 5433828, 7010154, 8503363]
INFO - main:201 - * adjusted stop_df: [3584087, 5054280, 6501182, 8077508, 9147519]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00004 ses-11 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [2849005, 2863445, 2897086, 2911526, 3185104, 4535561, 5947063, 7407633]
INFO - main:184 - * stop_df: [2851004, 2865444, 2899085, 2913525, 4253377, 5603835, 7015336, 8475906]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [3186024, 4536481, 5947983, 7408553]
INFO - main:201 - * adjusted stop_df: [4253379, 5603836, 7015337, 8475907]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00004 ses-14 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [1313261, 1327701, 1361286, 1375725, 1581949, 2928978, 4264683, 5566988]
INFO - main:184 - * stop_df: [1315259, 1329699, 1363284, 1377724, 2650222, 3997251, 5332956, 6635261]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [1582869, 2929898, 4265603, 5567908]
INFO - main:201 - * adjusted stop_df: [2650223, 3997252, 5332957, 6635262]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00004 ses-15 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5333
INFO - main:183 - * start_df: [2506344, 2520784, 2554406, 2568845, 2828176, 4458860, 5806149, 7144714, 8614440]
INFO - main:184 - * stop_df: [2508342, 2522782, 2556404, 2570844, 3886825, 5527134, 6874423, 8212988, 9259515]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [2829096, 4459780, 5807069, 7145634, 8615360]
INFO - main:201 - * adjusted stop_df: [3886826, 5527135, 6874424, 8212989, 9259517]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00004 ses-17 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [2379821, 2394261, 2427876, 2442316, 2964437, 4424266, 5890340, 7336685, 8747695]
INFO - main:184 - * stop_df: [2381820, 2396260, 2429874, 2444314, 4032711, 5492539, 6958613, 8404958, 9392770]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [2965357, 4425186, 5891260, 7337605, 8748615]
INFO - main:201 - * adjusted stop_df: [4032712, 5492541, 6958615, 8404959, 9392772]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00004 ses-18 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [214975, 229416, 263140, 277579, 537953, 2093023, 3569041, 5118556, 6483006]
INFO - main:184 - * stop_df: [216975, 231414, 265139, 279578, 1606207, 3161274, 4637294, 6186809, 7128069]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [214976, 537954, 2093943, 3569042, 5118557, 6483007]
INFO - main:201 - * adjusted stop_df: [216976, 1606207, 3161276, 4637295, 6186810, 7128070]
INFO - main:202 - * total of 6 runs
INFO - main:217 - runs shorter than 300 sec: sub-00004 ses-18 [0] - run number in python order
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [1, 2, 3, 4, 5], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00005 ses-01 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [4329934, 4344374, 4377828, 4392268, 4660460, 6141014, 7713761, 9365986, 11211866]
INFO - main:184 - * stop_df: [4331932, 4346372, 4379826, 4394266, 5728734, 7209288, 8782035, 10434260, 11856942]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [4661380, 6141934, 7714681, 9366906, 11212786]
INFO - main:201 - * adjusted stop_df: [5728735, 7209289, 8782036, 10434261, 11856943]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00005 ses-02 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [2001090, 2015530, 2049104, 2063543, 2343970, 4411556, 6097843, 7391134]
INFO - main:184 - * stop_df: [2003089, 2017529, 2051102, 2065542, 3412244, 5479829, 7166116, 8459407]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [2344890, 4412476, 6098763, 7392054]
INFO - main:201 - * adjusted stop_df: [3412245, 5479831, 7166117, 8459409]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00005 ses-04 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [2585103, 2599543, 2632999, 2647439, 2880669, 4290821, 5767268, 7142213, 8611259]
INFO - main:184 - * stop_df: [2587101, 2601541, 2634998, 2649438, 3948943, 5359094, 6835542, 8210486, 9256335]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [2881589, 4291741, 5768188, 7143133, 8612179]
INFO - main:201 - * adjusted stop_df: [3948944, 5359096, 6835543, 8210488, 9256336]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00005 ses-05 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [1317542, 1331982, 1365441, 1379881, 1621475, 3175481, 4507634, 5795294]
INFO - main:184 - * stop_df: [1319541, 1333981, 1367440, 1381880, 2689749, 4243755, 5575907, 6863568]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [1622395, 3176401, 4508554, 5796214]
INFO - main:201 - * adjusted stop_df: [2689751, 4243756, 5575909, 6863569]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00005 ses-07 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [3823455, 3837895, 3871606, 3886046, 4220645, 5687352, 7109563, 8550623, 10128411]
INFO - main:184 - * stop_df: [3825453, 3839893, 3873605, 3888045, 5288919, 6755626, 8177836, 9618896, 10773486]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [4221565, 5688272, 7110483, 8551543, 10129331]
INFO - main:201 - * adjusted stop_df: [5288920, 6755627, 8177837, 9618898, 10773487]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00005 ses-08 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [279627, 294067, 327664, 342103, 552168, 1952808, 3271413, 5093810]
INFO - main:184 - * stop_df: [281625, 296065, 329662, 344102, 1620441, 3021080, 4339686, 6162083]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [553088, 1953728, 3272333, 5094730]
INFO - main:201 - * adjusted stop_df: [1620442, 3021082, 4339687, 6162084]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00005 ses-09 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [3205187, 3219627, 3253286, 3267726, 3531515, 5131357, 6687008, 8240912]
INFO - main:184 - * stop_df: [3207185, 3221625, 3255284, 3269724, 4599788, 6199630, 7755281, 9309185]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [3532435, 5132277, 6687928, 8241832]
INFO - main:201 - * adjusted stop_df: [4599789, 6199631, 7755282, 9309186]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00005 ses-11 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [2061609, 2076049, 2109692, 2124131, 2529532, 4017770, 5530618, 7049087, 8619675]
INFO - main:184 - * stop_df: [2063607, 2078047, 2111690, 2126130, 3597805, 5086044, 6598891, 8117360, 9264750]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [2530452, 4018690, 5531538, 7050007, 8620595]
INFO - main:201 - * adjusted stop_df: [3597806, 5086045, 6598892, 8117362, 9264751]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00005 ses-12 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [4978317, 4992757, 5026413, 5040853, 5237938, 6744215, 8191749, 9883699]
INFO - main:184 - * stop_df: [4980316, 4994756, 5028412, 5042852, 6306211, 7812489, 9260022, 10951973]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [5238858, 6745135, 8192669, 9884619]
INFO - main:201 - * adjusted stop_df: [6306213, 7812490, 9260023, 10951974]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00005 ses-13 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [1404241, 1418681, 1452328, 1466768, 1722868, 3295772, 4756579, 6070860, 7861450]
INFO - main:184 - * stop_df: [1406239, 1420679, 1454326, 1468766, 2791142, 4364045, 5824852, 7139133, 8506526]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [1723788, 3296692, 4757499, 6071780, 7862370]
INFO - main:201 - * adjusted stop_df: [2791143, 4364046, 5824854, 7139135, 8506527]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00005 ses-16 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [1691705, 1706145, 1739898, 1754338, 2059810, 3696239, 5330421, 6676458, 8290784]
INFO - main:184 - * stop_df: [1693704, 1708144, 1741897, 1756337, 3128083, 4764512, 6398694, 7744731, 8935860]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [2060730, 3697158, 5331341, 6677378, 8291704]
INFO - main:201 - * adjusted stop_df: [3128085, 4764513, 6398695, 7744732, 8935861]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00005 ses-17 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 0
INFO - main:183 - * start_df: []
INFO - main:184 - * stop_df: []
INFO - main:185 - * total of 0 runs
INFO - main:200 - * adjusted start_df: []
INFO - main:201 - * adjusted stop_df: []
INFO - main:202 - * total of 0 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00005 ses-18 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [1119061, 1133501, 1182467, 1196907, 1443168, 2787756, 4265794, 5773135, 7351186]
INFO - main:184 - * stop_df: [1121060, 1135500, 1184466, 1198906, 2511442, 3856030, 5334068, 6841408, 7996262]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [1444088, 2788676, 4266714, 5774055, 7352106]
INFO - main:201 - * adjusted stop_df: [2511443, 3856031, 5334069, 6841409, 7996263]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00005 ses-19 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [1639368, 1653808, 1687452, 1701892, 2020684, 3635605, 5148844, 6584813]
INFO - main:184 - * stop_df: [1641367, 1655807, 1689451, 1703891, 3088957, 4703879, 6217117, 7653086]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [2021604, 3636525, 5149764, 6585733]
INFO - main:201 - * adjusted stop_df: [3088958, 4703880, 6217118, 7653087]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00006 ses-01 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4805
INFO - main:183 - * start_df: [1514512, 1528952, 1562569, 1577009, 3668987, 4324745, 5936568, 7465659, 8919086]
INFO - main:184 - * stop_df: [1516511, 1530950, 1564568, 1579008, 3818185, 5393017, 7004840, 8533931, 9987359]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [3669907, 4325665, 5937488, 7466579, 8920006]
INFO - main:201 - * adjusted stop_df: [3818187, 5393019, 7004841, 8533932, 9987360]
INFO - main:202 - * total of 5 runs
INFO - main:217 - runs shorter than 300 sec: sub-00006 ses-01 [0] - run number in python order
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00006 ses-02 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 909
INFO - main:183 - * start_df: [8209353, 8223793, 8257310, 8271750, 8565436, 10721734]
INFO - main:184 - * stop_df: [8211352, 8225792, 8259308, 8273748, 8755114, 11366809]
INFO - main:185 - * total of 6 runs
INFO - main:200 - * adjusted start_df: [8566356, 10722654]
INFO - main:201 - * adjusted stop_df: [8755115, 11366810]
INFO - main:202 - * total of 2 runs
INFO - main:217 - runs shorter than 300 sec: sub-00006 ses-02 [0] - run number in python order
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00006 ses-03 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [4174978, 4189418, 4223003, 4237443, 4550824, 6110353, 7610407, 8965490]
INFO - main:184 - * stop_df: [4176977, 4191417, 4225001, 4239441, 5619096, 7178625, 8678679, 10033763]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [4551744, 6111273, 7611327, 8966410]
INFO - main:201 - * adjusted stop_df: [5619097, 7178627, 8678681, 10033764]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00006 ses-05 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [343837, 358276, 391966, 406406, 630832, 2174107, 3548142, 5023621]
INFO - main:184 - * stop_df: [345835, 360275, 393965, 408405, 1699104, 3242379, 4616414, 6091894]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [631752, 2175027, 3549062, 5024541]
INFO - main:201 - * adjusted stop_df: [1699105, 3242380, 4616416, 6091895]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00006 ses-08 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [581737, 596176, 629885, 644324, 779948, 2215609, 3635858, 4964521]
INFO - main:184 - * stop_df: [583735, 598175, 631883, 646323, 1848221, 3283883, 4704131, 6032794]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [780868, 2216529, 3636778, 4965441]
INFO - main:201 - * adjusted stop_df: [1848222, 3283884, 4704133, 6032795]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00006 ses-09 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [2114156, 2128596, 2162415, 2176855, 2419790, 3757063, 5280872, 8365040]
INFO - main:184 - * stop_df: [2116155, 2130595, 2164414, 2178854, 3488063, 4825336, 6349145, 9433313]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [2420710, 3757983, 5281792, 8365960]
INFO - main:201 - * adjusted stop_df: [3488064, 4825337, 6349146, 9433314]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00006 ses-10 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5325
INFO - main:183 - * start_df: [1304450, 2790536, 4222113, 5789407]
INFO - main:184 - * stop_df: [1054878, 2372724, 3858810, 5290386, 6434482]
INFO - main:185 - * total of 4 runs
INFO - main:200 - * adjusted start_df: [1305370, 2791456, 4223033, 5790327]
INFO - main:201 - * adjusted stop_df: [1054880, 2372726, 3858811, 5290388, 6434483]
INFO - main:202 - * total of 4 runs
ERROR - main:209 - start and stop datapoints don't match
INFO - main:134 - __________________sub-00006 ses-11 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [3296961, 3311401, 3345162, 3359602, 3485406, 4759623, 6025259, 7422136, 8795114]
INFO - main:184 - * stop_df: [3298960, 3313400, 3347161, 3361601, 4553680, 5827896, 7093532, 8490409, 9440189]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [3486326, 4760543, 6026179, 7423056, 8796034]
INFO - main:201 - * adjusted stop_df: [4553681, 5827898, 7093533, 8490410, 9440190]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00006 ses-12 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [928722, 943162, 976803, 991243, 1096702, 2814349, 4209246, 5628518]
INFO - main:184 - * stop_df: [930720, 945160, 978802, 993242, 2164977, 3882623, 5277520, 6696792]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [1097622, 2815269, 4210166, 5629438]
INFO - main:201 - * adjusted stop_df: [2164978, 3882625, 5277521, 6696793]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00006 ses-14 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [3189874, 3204314, 3237851, 3252291, 3480552, 5293271, 6722329, 8302073]
INFO - main:184 - * stop_df: [3191873, 3206313, 3239850, 3254290, 4548826, 6361545, 7790603, 9370346]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [3481472, 5294191, 6723249, 8302993]
INFO - main:201 - * adjusted stop_df: [4548827, 6361547, 7790604, 9370348]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00006 ses-15 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [2399471, 2413911, 2447541, 2461981, 3108273, 5063785, 6781896, 8459880, 9928782]
INFO - main:184 - * stop_df: [2401472, 2415912, 2449542, 2463982, 4176527, 6132039, 7850149, 9528133, 10573847]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [2399472, 2413912, 2447542, 2461982, 3108274, 5063786, 6781897, 8459881, 9928783]
INFO - main:201 - * adjusted stop_df: [2401472, 2415912, 2449542, 2463982, 4176527, 6132039, 7850149, 9528133, 10573847]
INFO - main:202 - * total of 9 runs
INFO - main:217 - runs shorter than 300 sec: sub-00006 ses-15 [0, 1, 2, 3] - run number in python order
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [4, 5, 6, 7, 8], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00007 ses-04 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [3462236, 3476676, 3510275, 3524715, 3816862, 5441921, 6962880, 8508698]
INFO - main:184 - * stop_df: [3464234, 3478674, 3512274, 3526714, 4885136, 6510195, 8031153, 9576972]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [3817782, 5442841, 6963800, 8509618]
INFO - main:201 - * adjusted stop_df: [4885137, 6510196, 8031155, 9576973]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00007 ses-05 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [1387681, 1402121, 1435854, 1450293, 1722794, 3190824, 4934031, 6576195, 8051936]
INFO - main:184 - * stop_df: [1389680, 1404119, 1437852, 1452292, 2791068, 4259097, 6002305, 7644469, 8697011]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [1723714, 3191744, 4934951, 6577115, 8052856]
INFO - main:201 - * adjusted stop_df: [2791070, 4259099, 6002306, 7644470, 8697013]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00007 ses-06 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [772101, 786541, 820212, 834652, 944847, 2279183, 3688424, 5081739]
INFO - main:184 - * stop_df: [774100, 788540, 822211, 836651, 2013121, 3347456, 4756697, 6150012]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [945767, 2280103, 3689344, 5082659]
INFO - main:201 - * adjusted stop_df: [2013122, 3347458, 4756698, 6150014]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00007 ses-07 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [985097, 999537, 1033335, 1047774, 1230800, 2640696, 4032299, 5501776, 7005569]
INFO - main:184 - * stop_df: [987095, 1001535, 1035333, 1049773, 2299073, 3708969, 5100572, 6570049, 7650644]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [1231720, 2641616, 4033219, 5502696, 7006489]
INFO - main:201 - * adjusted stop_df: [2299074, 3708971, 5100574, 6570050, 7650645]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00007 ses-08 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5395
INFO - main:183 - * start_df: [2221216, 2235656, 2269507, 2283946, 2424603, 3883129, 5324324, 6727537, 8037793, 8448316]
INFO - main:184 - * stop_df: [2223215, 2237655, 2271505, 2285945, 3492877, 4951402, 6392597, 7795810, 8085792, 9093391]
INFO - main:185 - * total of 10 runs
INFO - main:200 - * adjusted start_df: [2425523, 3884049, 5325244, 6728457, 8038713, 8449236]
INFO - main:201 - * adjusted stop_df: [3492878, 4951404, 6392599, 7795811, 8085793, 9093392]
INFO - main:202 - * total of 6 runs
INFO - main:217 - runs shorter than 300 sec: sub-00007 ses-08 [4] - run number in python order
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 5], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00007 ses-10 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4640
INFO - main:183 - * start_df: [534410, 1908793, 3219153, 4569028]
INFO - main:184 - * stop_df: [1602684, 2977066, 4287427, 5637301]
INFO - main:185 - * total of 4 runs
INFO - main:200 - * adjusted start_df: [535330, 1909713, 3220073, 4569948]
INFO - main:201 - * adjusted stop_df: [1602685, 2977068, 4287428, 5637302]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00007 ses-11 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [2859171, 2873611, 2907269, 2921709, 3170815, 4621015, 5989915, 7335475, 8720654]
INFO - main:184 - * stop_df: [2861170, 2875610, 2909268, 2923708, 4239090, 5689289, 7058189, 8403749, 9365730]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [3171735, 4621935, 5990835, 7336395, 8721574]
INFO - main:201 - * adjusted stop_df: [4239091, 5689291, 7058191, 8403750, 9365731]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00007 ses-12 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 4644
INFO - main:183 - * start_df: [992993, 1007433, 1041134, 1055574, 1573152, 2996178, 4479476, 5945523]
INFO - main:184 - * stop_df: [994992, 1009431, 1043133, 1057573, 2641427, 4064453, 5547750, 7013797]
INFO - main:185 - * total of 8 runs
INFO - main:200 - * adjusted start_df: [1574072, 2997098, 4480396, 5946443]
INFO - main:201 - * adjusted stop_df: [2641428, 4064454, 5547751, 7013799]
INFO - main:202 - * total of 4 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00007 ses-13 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [1260948, 1275387, 1309184, 1323623, 2722907, 4607664, 6067444, 7383025, 8772501]
INFO - main:184 - * stop_df: [1262948, 1277386, 1311183, 1325624, 3791161, 5675918, 7135698, 8451279, 9417564]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [1275388, 1309185, 1323624, 2722908, 4607665, 6067445, 7383026, 8772502]
INFO - main:201 - * adjusted stop_df: [1277388, 1311185, 1325624, 3791161, 5675918, 7135698, 8451279, 9417566]
INFO - main:202 - * total of 8 runs
INFO - main:217 - runs shorter than 300 sec: sub-00007 ses-13 [0, 1, 2] - run number in python order
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [3, 4, 5, 6, 7], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
INFO - main:134 - __________________sub-00007 ses-14 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 3484
INFO - main:183 - * start_df: [3337146, 3351585, 3385184, 3399623, 3990167, 5350662, 6853475]
INFO - main:184 - * stop_df: [3339144, 3353584, 3387183, 3401622, 5058420, 6418913, 7921727]
INFO - main:185 - * total of 7 runs
INFO - main:200 - * adjusted start_df: [3990168, 5351582, 6854395]
INFO - main:201 - * adjusted stop_df: [5058421, 6418914, 7921728]
INFO - main:202 - * total of 3 runs
INFO - main:229 - __________________ :+: FINISHED :+: __________________
INFO - main:134 - __________________sub-00007 ses-16 __________________
INFO - main:135 - file exists! -- starting transformation: 
INFO - main:162 - number of spikes within experiment: 5344
INFO - main:183 - * start_df: [1484477, 1498917, 1532629, 1547069, 2078100, 3559187, 4990932, 6542067, 7828284]
INFO - main:184 - * stop_df: [1486476, 1500916, 1534628, 1549068, 3146351, 4627439, 6059184, 7610318, 8473347]
INFO - main:185 - * total of 9 runs
INFO - main:200 - * adjusted start_df: [2079020, 3560107, 4991852, 6542987, 7829204]
INFO - main:201 - * adjusted stop_df: [3146352, 4627440, 6059185, 7610319, 8473348]
INFO - main:202 - * total of 5 runs
ERROR - main:231 - number of complete runs do not match scan notes
ERROR - main:232 - clean_runlist: [0, 1, 2, 3, 4], scannote_reference.columns: Index(['run-1', 'run-2', 'run-3', 'run-4'], dtype='object')
